# Generated by Django 6.0.7 on 2026-08-09 21:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('repayment_term', models.PositiveSmallIntegerField(choices=[(6, '6 months'), (12, '12 months'), (24, '24 months'), (36, '36 months')])),
                ('purpose', models.TextField(max_length=500)),
                ('employment', models.CharField(max_length=150)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('previous_default', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes'), ('AZKABAN', 'I prefer not to discuss Azkaban')], max_length=20, verbose_name='Have you previously defaulted on a loan?')),
                ('owes_goblins', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes'), ('UNPROVEN', 'Not any that can prove it')], max_length=20, verbose_name='Do you currently owe money to any goblins?')),
                ('dragons_on_property', models.CharField(choices=[('0', '0'), ('1', '1'), ('2_PLUS', '2+'), ('DEFINE_RESIDE', 'Define "reside"')], max_length=20, verbose_name='How many dragons currently reside on your property?')),
                ('unauthorized_vault_entry', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes'), ('LEGAL_ADVICE', 'My solicitor has advised me not to answer this question')], max_length=20, verbose_name='Have you ever entered a Gringotts vault without authorization?')),
                ('financial_decision_rating', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('QUESTIONABLE', 'Questionable'), ('NIMBUS', 'I am applying for this loan to buy a Nimbus')], max_length=20, verbose_name='Please rate your financial decision-making.')),
                ('income_loss_repayment', models.CharField(choices=[('SAVINGS', 'Savings'), ('SELL_ASSETS', 'Sell assets'), ('FAMILY_SUPPORT', 'Family support'), ('POLYJUICE', 'A highly elaborate plan involving Polyjuice Potion')], max_length=20, verbose_name='If your income disappeared tomorrow, how would you repay Gringotts?')),
                ('collateral', models.CharField(choices=[('PROPERTY', 'Property'), ('GOLD', 'Gold'), ('MAGICAL_OBJECTS', 'Valuable magical objects'), ('FAMILY_HEIRLOOM', 'Family heirloom'), ('FIRST_BORN', 'First-born child'), ('WAIT_WHAT', 'Wait, WHAT?')], max_length=20, verbose_name='What are you willing to offer as collateral?')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='loan_requested_amount_positive'), models.CheckConstraint(condition=models.Q(('monthly_income__gte', 0)), name='loan_monthly_income_non_negative')],
            },
        ),
    ]
